### PR TITLE
Google Cardboard

### PR DESCRIPTION
**Pull request by lukebarnard1**
(In response to the email from Tom)

I thought I'd just make this pull request so that we can discuss what to do with this fork before we merge it in. There are a few things that are to be desired:
- [ ] Instructions for using the stereo view
- [ ] Moving the stereo mode button to a more suitable place
- [ ] Better initial camera position in stereo view
- [ ] Revert to "Autoforwarding" instead of the current "lean forward to go forward" approach

### CODE REVIEW

**Comment by tpmccauley** [comment]
I've working on merging this PR with the following changes:
* moved changes in CombinedCamera.js to controls.js
* use default DeviceControls (i.e. no zooming on up/down motion; there is just a simple slow pan forward)
* Moved the stereo button and on click, a modal pops up with some explanation. A button on the modal starts the view.
* The initial camera position not at the origin but now further along the beam axis

Otherwise, all other functionality is there. 
I am testing at http://cmsdoc.cern.ch/~mccauley/ispy-webgl-cardboard

**Comment by tpmccauley** [comment]
After testing I think it is ready for release.

**Comment by lukebarnard1** [comment]
The online test looks good to me. No problems, Tom :smile:

**Comment by tpmccauley** [comment]
Actually there were a couple bugs I missed:
* Handling of axes
* Had to use Object.assign when switching renderer and controls to stereo
The latter was tricky as it only showed up when the background color was inverted.

Now it looks ready, but release on Friday evening? Never.

**Pull request merged**
