### PR TITLE
Add the GEM in ispy-webgl

### PR DESCRIPTION
**Pull request by SeungJunLee0**
If you have any question or find something wrong.

please tell me.

Here is mail address seungjun.lee@cern.ch , seungjunlee15@gmail.ocm

Thank you

### CODE REVIEW

**Comment by tpmccauley** [comment]
Thanks @SeungJunLee0 

I am working on a new release right now as well as a threejs upgrade so have changed the target branch to r125. 

There is one small conflict in the index.html (and Default.htm) that I can resolve. I will also convert the gem geometry to glTF and use that instead once I merge.

**Comment by SeungJunLee0** [comment]
@tpmccauley 
what is the glTF??? i never heard about it...

**Comment by tpmccauley** [comment]
glTF: https://en.wikipedia.org/wiki/GlTF

I have opted to start to handle geometries using this format. It is smaller than the equivalent obj and js and also one doesn't have to created the geometry from corners everytime. 

Once gem.js is loaded I can export to something like gem.glb (binary glTF) and then use that file in the future.

**Comment by tpmccauley** [comment]
@SeungJunLee0 also it (using glTF) makes life easier for handling geometries over different possible eras, especially as we will be (and are) handling data in Run2 and Run3 configurations

**Comment by SeungJunLee0** [comment]
@tpmccauley 
in short, you will change the gem.js to  gem.glb.
and remove the these obj files( geometry/muon-barrel.obj, geometry/muon-endcap-minus.obj, geometry/muon-endcap-plus.obj) ?

**Comment by tpmccauley** [comment]
@SeungJunLee0 

Yes, I will create a GEM glb file but need the information first from gem.js.

Geometry is not used anymore. Rather, one must use BufferGeometry. 

For an example see https://github.com/cms-outreach/ispy-webgl/blob/r125/js/objects-draw.js#L1

**Comment by SeungJunLee0** [comment]
@tpmccauley 
Thank you very much!!
is there anything i have to do?

**Comment by tpmccauley** [comment]
@SeungJunLee0 Just resolve the conflicts in index.html and Default.htm (rm the script tags with all the muon geometries except gem.js) and push. Then I will merge.

**Comment by SeungJunLee0** [comment]
i remove the script tag(gem.js in Default.htm and index.html)

is this the solution that you want??

**Comment by tpmccauley** [comment]
@SeungJunLee0 Thanks. Actually keep gem.js but remove the other muon ones like rpc.js. This will work though. I will have to make a few fixes but they are simple. Will merge.

**Comment by tpmccauley** [comment]
@SeungJunLee0 I've made some changes and made glb files. I will get back to you with check when I test the GEM objects themselves. Thanks!

image

**Comment by SeungJunLee0** [comment]
@tpmccauley 
you're welcome.
And if you need the ~~~.ig files(which contain GEMSegment, GEMDigis,GEMRechits.... )
i will sent you.

**Comment by tpmccauley** [comment]
@SeungJunLee0 yes, please email them to me or cernbox or dropbox. Also, I had a comment on the analyzers regarding the input file.

**Comment by SeungJunLee0** [comment]
@tpmccauley  
i sent the ig files one is MC data another one is MWGR data
and what the comments???

**Comment by tpmccauley** [comment]
Oops. Comment was pending as part of review. You should get it now. 

Now that I have ig files you have answered this comment anyway.

**Pull request merged**
